sentiment_analysis:
  huggingface_model_id: stevhliu/my_awesome_model
  trained_model_path: None
  task: sentiment-analysis

topic_modeling:
  trained_path: /Users/duongtrongchi/engineering/personal/Moodlens/training_pipeline/topic_modeling/topic_modeling/trained_model/bert_topic_modeling_v0.0.0